#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

if [ ! -f /var/www/.env ]; then
    cp /var/www/.env.docker /var/www/.env
fi

chmod -R ugo+rw /.composer

composer install

chown -R $WWWUSER:$WWWGROUP /var/www

/wait && php artisan migrate && php artisan koala:import

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
